repository:
  name: insecure-repo
  visibility: public
  allow_merge_commit: true
  allow_squash_merge: true
  allow_rebase_merge: true
  delete_branch_on_merge: false
  web_commit_signoff_required: false
  security_and_analysis:
    secret_scanning:
      status: disabled
    secret_scanning_push_protection:
      status: disabled
    advanced_security:
      status: disabled
